### ISSUE TITLE
Unable to run in engine dummy application

### ISSUE THREAD

**Issue by yld** [ptyagi16/guard-consistency_fail#2]
I'd like to be able to run consistency fail in another directory i could specify in an option.

**Comment by ptyagi16** [comment]
Closing as fixed by https://github.com/trptcolin/consistency_fail/pull/38

**Comment by yld** [comment]
It is not fixed as there is no way to pass the target directory to guard-consistency_fail

**Comment by ptyagi16** [comment]
OK, Re-opening for now
